# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-19 05:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_auto_20170519_0535'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Inventory',
            new_name='Movement',
        ),
        migrations.AlterField(
            model_name='item',
            name='code',
            field=models.IntegerField(unique=True),
        ),
    ]
