# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-06 03:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_auto_20170519_0549'),
    ]

    operations = [
        migrations.AddField(
            model_name='movement',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movement',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
