# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-13 22:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('binnacle', '0003_type_accident_detail'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prevent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=300)),
                ('type', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='binnacle.Type_Accident')),
            ],
        ),
    ]
