# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-09 19:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accidente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edad', models.IntegerField()),
                ('years', models.DateField()),
                ('hour', models.TimeField()),
                ('type', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('observation', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Broken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accident', models.CharField(max_length=50)),
                ('repose', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Working',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('area', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='binnacle.Area')),
            ],
        ),
        migrations.CreateModel(
            name='Workstation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='working',
            name='workstation',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='binnacle.Workstation'),
        ),
        migrations.AddField(
            model_name='broken',
            name='working',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='binnacle.Working'),
        ),
        migrations.AddField(
            model_name='accidente',
            name='area',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='binnacle.Area'),
        ),
        migrations.AddField(
            model_name='accidente',
            name='broken',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='binnacle.Broken'),
        ),
        migrations.AddField(
            model_name='accidente',
            name='workstation',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='binnacle.Workstation'),
        ),
    ]
