# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-13 05:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('binnacle', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accident',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('date', models.DateField()),
                ('hour', models.TimeField()),
                ('description', models.TextField()),
                ('observation', models.CharField(max_length=100)),
                ('repose', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Type_Accident',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='accidente',
            name='area',
        ),
        migrations.RemoveField(
            model_name='accidente',
            name='broken',
        ),
        migrations.RemoveField(
            model_name='accidente',
            name='workstation',
        ),
        migrations.RemoveField(
            model_name='broken',
            name='working',
        ),
        migrations.AddField(
            model_name='area',
            name='detail',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workstation',
            name='detail',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Accidente',
        ),
        migrations.DeleteModel(
            name='Broken',
        ),
        migrations.AddField(
            model_name='accident',
            name='area',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='binnacle.Area'),
        ),
        migrations.AddField(
            model_name='accident',
            name='type',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='binnacle.Type_Accident'),
        ),
        migrations.AddField(
            model_name='accident',
            name='working',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='binnacle.Working'),
        ),
        migrations.AddField(
            model_name='accident',
            name='workstation',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='binnacle.Workstation'),
        ),
    ]
