# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-13 05:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('binnacle', '0002_auto_20170613_0110'),
    ]

    operations = [
        migrations.AddField(
            model_name='type_accident',
            name='detail',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
